name: markaa
description: Ecommerce app for multi-vendor

publish_to: 'none'

version: 1.6.3+33

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  adjust_sdk: ^4.28.0
  algolia: ^1.0.1
  app_tracking_transparency: ^2.0.1
  auto_size_text: ^2.1.0
  badges: ^1.2.0
  bloc: ^7.0.0
  cached_network_image: ^3.0.0
  carousel_slider: ^3.0.0
  cloud_firestore: ^1.0.6
  connectivity: ^3.0.3
  cool_alert: ^1.1.0
  cupertino_back_gesture: ^0.1.0
  cupertino_icons: ^1.0.2
  device_info: ^2.0.0
  easy_localization: ^3.0.0
  enum_to_string: ^2.0.1
  equatable: ^2.0.0
  faker: ^1.3.0
  firebase_analytics: ^8.0.2
  firebase_auth: ^1.1.1
  firebase_core: ^1.0.4
  firebase_dynamic_links: ^2.0.2
  firebase_messaging: ^10.0.0
  firebase_storage: ^8.0.4
  flushbar: ^1.10.4
  flutter_bloc: ^7.0.0
  flutter_facebook_login: ^3.0.0
  flutter_html: ^1.3.0
  flutter_launcher_icons: ^0.9.0
  flutter_local_notifications: ^5.0.0+1
  flutter_rating_bar: ^4.0.0
  flutter_screenutil: ^5.0.0+2
  flutter_spinkit: ^5.0.0
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^0.22.0
  flutter_swiper: ^1.1.6
  font_awesome_flutter: ^9.0.0
  geolocator: ^7.0.3
  google_fonts: ^2.0.0
  google_maps_flutter: ^2.0.3
  google_sign_in: ^5.0.2
  hexcolor: ^2.0.3
  image_cropper: ^1.4.0
  image_picker: ^0.7.4
  in_app_review: ^2.0.2
  infinite_carousel: ^1.0.1
  intl_phone_number_input: ^0.7.0+1
  inview_notifier_list: ^2.0.0
  kommunicate_flutter: ^1.1.7
  lottie: ^1.0.1
  meta: ^1.3.0
  photo_view: ^0.11.1
  progress_dialog: ^1.2.4
  progressive_image: ^2.0.0
  pull_to_refresh: ^1.6.2
  share: ^2.0.1
  shared_preferences: ^2.0.5
  shimmer: ^2.0.0
  sign_in_with_apple: ^3.0.0
  sliding_sheet: ^0.5.0
  sliding_up_panel: ^1.0.2
  smooth_page_indicator: ^0.2.0
  snapping_sheet: ^3.1.0
  string_validator: ^0.3.0
  url_launcher: ^6.0.3
  webview_flutter: ^1.0.7
  zoom_widget: ^0.1.3

dependency_overrides:
  intl: ^0.17.0
  url_launcher: ^6.0.3
  flutter_svg: ^0.22.0
  quiver: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  dio: ^4.0.0
  dio_cache_interceptor: ^2.3.0
  provider: ^5.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  # image_path: "lib/public/launcher/ios-app-launcher-icon.png"
  image_path: "lib/public/launcher/app-launcher-icon.png"

flutter:

  uses-material-design: true

  assets:
    - lib/public/languages/
    - lib/public/images/
    - lib/public/images/flags/
    - lib/public/images/loading/
    - lib/public/icons/
    - lib/public/animations/
    - lib/public/launcher/

  fonts:
    - family: AvenirMedium
      fonts:
        - asset: lib/public/fonts/Avenir-Medium.ttf
    - family: AvenirBook
      fonts:
        - asset: lib/public/fonts/Avenir-Book.ttf
    - family: AvenirBlack
      fonts:
        - asset: lib/public/fonts/Avenir-Black.ttf
