name: markaa
description: Ecommerce app for multi-vendor

publish_to: 'none'

version: 1.8.0+40

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  adjust_sdk: ^4.28.0
  algolia: ^1.0.1
  app_tracking_transparency: ^2.0.1
  badges: ^2.0.1
  bloc: ^7.0.0
  cached_network_image: ^3.0.0
  carousel_slider: ^4.0.0
  cloud_firestore: ^2.5.2
  connectivity: ^3.0.3
  cupertino_back_gesture: ^0.1.0
  cupertino_icons: ^1.0.2
  device_info: ^2.0.0
  easy_localization: ^3.0.0
  enum_to_string: ^2.0.1
  equatable: ^2.0.0
  faker: ^2.0.0
  firebase_analytics: ^8.0.2
  firebase_auth: ^3.1.1
  firebase_core: ^1.0.4
  firebase_dynamic_links: ^2.0.2
  firebase_messaging: ^10.0.9
  firebase_storage: ^10.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_cache_manager: ^3.1.2
  flutter_facebook_auth: ^3.5.2
  flutter_html: ^2.1.2
  flutter_launcher_icons: ^0.9.0
  flutter_local_notifications: ^8.2.0
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.0
  flutter_screenutil: ^5.0.0+2
  flutter_spinkit: ^5.1.0
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^0.22.0
  flutter_swiper_null_safety: ^1.0.2
  font_awesome_flutter: ^9.0.0
  geolocator: ^7.7.0
  google_fonts: ^2.0.0
  google_maps_flutter: ^2.0.3
  google_sign_in: ^5.0.2
  hexcolor: ^2.0.3
  image_cropper: ^1.4.0
  image_picker: ^0.8.4
  in_app_review: ^2.0.2
  infinite_carousel: ^1.0.1
  intl_phone_number_input: ^0.7.0+1
  inview_notifier_list: ^2.0.0
  just_the_tooltip: ^0.0.7+6
  kommunicate_flutter: ^1.2.2
  lottie: ^1.0.1
  meta: ^1.3.0
  onesignal_flutter: ^3.2.3
  package_info_plus: ^1.0.6
  photo_view: ^0.12.0
  progress_dialog: ^1.2.4
  progressive_image: ^2.0.0
  pull_to_refresh: ^2.0.0
  share: ^2.0.1
  shared_preferences: ^2.0.5
  shimmer: ^2.0.0
  sign_in_with_apple: ^3.0.0
  sliding_sheet: ^0.5.0
  smooth_page_indicator: ^1.0.0+2
  snapping_sheet: ^3.1.0
  string_validator: ^0.3.0
  top_sliding_sheet:
    path: plugins/top_sliding_sheet-1.0.0
  url_launcher: ^6.0.3
  webview_flutter: ^2.0.13
  zoom_widget: ^0.2.1

dependency_overrides:
  intl: ^0.17.0
  url_launcher: ^6.0.3
  flutter_svg: ^0.22.0
  quiver: ^3.0.0
dev_dependencies:
  dio: ^4.0.0
  dio_cache_interceptor: ^3.0.1
  flutter_test:
    sdk: flutter
  provider: ^6.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  # image_path: "lib/public/launcher/ios-app-launcher-icon.png"
  image_path: "lib/public/launcher/app-launcher-icon.png"

flutter:

  uses-material-design: true

  assets:
    - lib/public/languages/
    - lib/public/images/
    - lib/public/images/flags/
    - lib/public/images/loading/
    - lib/public/icons/
    - lib/public/animations/
    - lib/public/launcher/

  fonts:
    - family: AvenirMedium
      fonts:
        - asset: lib/public/fonts/Avenir-Medium.ttf
    - family: AvenirBook
      fonts:
        - asset: lib/public/fonts/Avenir-Book.ttf
    - family: AvenirBlack
      fonts:
        - asset: lib/public/fonts/Avenir-Black.ttf
