name: ciga
description: Ecommerce app for multi-vendor

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_svg: ^0.18.1
  progress_dialog: ^1.2.4
  carousel_slider: ^2.2.1
  flutter_swiper: ^1.1.6
  smooth_page_indicator: ^0.2.0
  flutter_launcher_icons: ^0.7.5
  easy_localization: ^2.3.2
  cross_local_storage: ^1.1.1
  bloc: ^6.0.1
  equatable: ^1.2.3
  flutter_bloc: ^6.0.1
  meta: ^1.1.8
  badges: ^1.1.1
  google_sign_in: ^4.5.1
  # flutter_facebook_login: ^3.0.0
  enum_to_string: ^1.0.9
  string_validator: ^0.1.4
  google_fonts: ^1.1.0
  flutter_xlider: ^3.4.0
  isco_custom_widgets:
    git: https://github.com/iscojin/isco_flutter_custom_widgets.git
  intl_phone_number_input: ^0.4.6+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - lib/public/languages/
    - lib/public/images/
    - lib/public/icons/

  fonts:
    - family: AvenirMedium
      fonts:
        - asset: lib/public/fonts/Avenir-Medium.ttf
    - family: AvenirBook
      fonts:
        - asset: lib/public/fonts/Avenir-Book.ttf
    - family: AvenirBlack
      fonts:
        - asset: lib/public/fonts/Avenir-Black.ttf

